sonar.projectKey=byigitakbulut_AIorHuman_ML_Model
sonar.organization=byigitakbulut

# Projenin görünen ad?
sonar.projectName=AIorHuman_ML_Model

# Kaynak dosyalar?n nerede oldu?unu belirtir (. ?u anki dizin demek)
sonar.sources=.

# Python dosyalar? taranacak dil olarak belirtilir
sonar.language=py

# Kodlama format?
sonar.sourceEncoding=UTF-8

# Jupyter Notebook dosyalar?n? tarar
sonar.exclusions=**/*.ipynb